### PR TITLE
Fix of issue #101

### PR DESCRIPTION
**Pull request by MartinHlavna**
In case of ManyToMany relation, other side of relation will always be deleted when cascading removal, even if another relation exists.

In addition to this, there may be use cases in which you don't want to remove orphaned entities. Because of this, a new optional bool parameter orphanRemoval has been added to methods remove and detachXXX.

### CODE REVIEW

**Comment by jaumard** [comment]
please regenerate also the embedded example, it will be easier to see first if it works (generate something that at least compile) and will be able to see more easily what the output of this. Thanks

**Comment by tejainece** [comment]
I will review it, test it and publish it over the coming weekend. Sorry for the delay.

**Comment by hjJunior** [comment]
Any update here?

**Comment by tejainece** [comment]
Thanks for the pull request. It has been absorbed.

**Comment by tejainece** [comment]
Thanks for the pull request. It has been absorbed.

**Pull request closed without merging**
