### PR TITLE
Insert many query + sqflite

### PR DESCRIPTION
**Pull request by jaumard**
Beginning of #34 :) 

Don't hesitate to give feedback @tejainece as it's me first dig into the project ^^ might have did some shit lol

### CODE REVIEW

**Comment by jaumard** [comment]
tested locally on sqflite example and it works, I was able to insert multiple rows :)

**Comment by jaumard** [comment]
But no idea on how having deep insert with that :/

**Review by tejainece — APPROVED** [review]
LGTM

**Comment by tejainece** [comment]
Great work!

**Comment by jaumard** [comment]
thx :) this might break other adapter as I had a new method that need to be implemented by them :/ didn't check others

**Comment by tejainece** [comment]
Yes, I noticed. I will update other adapters. There are only three adapters for now: sqflite, postgres and mysql.

**Pull request merged**
