### PR TITLE
fix crash on preload all immutable list

### PR DESCRIPTION
**Pull request by jaumard**

### CODE REVIEW

**Comment by jaumard** [comment]
@tejainece let me know when you've publish this one please :) got this crash during public beta testing :/

**Review by tejainece — APPROVED** [review]
LGTM

**Comment by jaumard** [comment]
Please @tejainece can you publish this fix ?

**Comment by tejainece** [comment]
I will test it and publish over this weekend.

**Comment by tejainece** [comment]
Published!

**Pull request merged**
