### PR TITLE
Null Safe migration - legacyV3 branch

### PR DESCRIPTION
**Pull request by JamesMcIntosh**
This is a partial attempt at null migration. I have tested it out using Sqflite.

The local project dependencies have been set to use paths, this is just for testing it.
How is module dependency versioning handled for this project?

### CODE REVIEW

**Comment by tejainece** [comment]
Thanks for PR. I will review and merge it this weekend.

**Comment by zhibaiwei** [comment]
Expect to see the empty security version supported on the pub

**Comment by JamesMcIntosh** [comment]
@zhibaiwei could you please explain what you mean by "security version"

**Comment by zhibaiwei** [comment]
Null safety

**Comment by AlexBolot** [comment]
@tejainece If you could indeed merge this PR this weekend it would be great 🙌 , I need this update to solve a problem for my client !

**Comment by AlexBolot** [comment]
@tejainece Any update on this PR being merged ? 😃

**Comment by LempereurBenjamin** [comment]
@tejainece : Any update ? Thank you.

**Comment by dmiedev** [comment]
@tejainece Are you alive?

**Comment by Skuallpa** [comment]
@tejainece: Any chance to have this pull request merged soon?

**Pull request merged**
